[ColorEffects:Disabled]
Color=96,96,96
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=0
IntensityAmount=0.1
IntensityEffect=0

[ColorEffects:Inactive]
Color=112,111,110
ColorAmount=0.025
ColorEffect=0
ContrastAmount=0.1
ContrastEffect=0
IntensityAmount=0.025
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=@RG_C_SURFACE0@
BackgroundNormal=@RG_C_MANTLE@
DecorationFocus=@RG_C_ACCENT@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT@
ForegroundInactive=@RG_C_SUBTEXT0@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_TEXT@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_5@

[Colors:Complementary]
BackgroundAlternate=@RG_C_SURFACE1@
BackgroundNormal=@RG_C_CRUST@
DecorationFocus=@RG_C_ACCENT@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT@
ForegroundInactive=@RG_C_SUBTEXT0@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_TEXT@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_5@

[Colors:Header]
BackgroundAlternate=@RG_C_SURFACE0@
BackgroundNormal=@RG_C_MANTLE@
DecorationFocus=@RG_C_ACCENT@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT@
ForegroundInactive=@RG_C_SUBTEXT0@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_TEXT@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_5@

[Colors:Selection]
BackgroundAlternate=@RG_C_ACCENT_FG@
BackgroundNormal=@RG_C_ACCENT@
DecorationFocus=@RG_C_ACCENT_DIM@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT_FG@
ForegroundInactive=@RG_C_TEXT@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_ACCENT_FG@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_13@

[Colors:Tooltip]
BackgroundAlternate=@RG_C_SURFACE0@
BackgroundNormal=@RG_C_MANTLE@
DecorationFocus=@RG_C_ACCENT@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT@
ForegroundInactive=@RG_C_SUBTEXT0@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_TEXT@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_5@

[Colors:Window]
BackgroundAlternate=@RG_C_SURFACE0@
BackgroundNormal=@RG_C_BG@
DecorationFocus=@RG_C_ACCENT@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT@
ForegroundInactive=@RG_C_SUBTEXT0@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_TEXT@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_5@

[Colors:View]
BackgroundAlternate=@RG_C_SURFACE0@
BackgroundNormal=@RG_C_BG@
DecorationFocus=@RG_C_ACCENT@
DecorationHover=@RG_C_ACCENT_DIM@
ForegroundActive=@RG_C_ACCENT@
ForegroundInactive=@RG_C_SUBTEXT0@
ForegroundLink=@RG_C_ACCENT_DIM@
ForegroundNegative=@RG_C_1@
ForegroundNeutral=@RG_C_3@
ForegroundNormal=@RG_C_TEXT@
ForegroundPositive=@RG_C_2@
ForegroundVisited=@RG_C_5@

[General]
ColorScheme=@PALETTE_SHORT@
Name=@PALETTE_NAME@
Org=devuan-kde-setup
blur=true
contrast=1

[WM]
activeBackground=@RG_C_MANTLE@
activeBlend=@RG_C_ACCENT@
activeForeground=@RG_C_TEXT@
inactiveBackground=@RG_C_CRUST@
inactiveBlend=@RG_C_OVERLAY0@
inactiveForeground=@RG_C_SUBTEXT0@