#!/usr/bin/env bash
# =======================================================
# Plasma Panel — a clean, organized, productive panel
# -------------------------------------------------------
# Rebuilds the Plasma panel into one single clean floating
# bar: a small breathing spacer, Kickoff, your pinned apps
# (Konsole, Dolphin, Firefox ESR, VLC, Okular — only the
# ones actually installed are added), an icon-only task
# manager for running apps, an expanding spacer, the system
# tray, a compact clock, and show-desktop.
#
# Builds and tears down the panel entirely through the
# SAME supported Plasmashell scripting API that KDE's own
# migration scripts use (desktops()/panels()/new Panel()/
# addWidget()/writeConfig()/remove()) — no hand-editing of
# plasma-org.kde.plasma.desktop-appletsrc.
#
# Safe/reversible by design:
#   - the current config is backed up BEFORE anything runs
#     (restore = swap it back, then log out/in or run the
#     plasmashell restart printed below);
#   - every change applies live via D-Bus, so nothing needs
#     root and nothing takes effect until the script runs;
#   - pinned apps are resolved against what's installed, so
#     a missing VSCodium/etc. is skipped cleanly instead of
#     leaving a dead icon.
#
# Usage: scripts/plasmaPanel.sh [--dry-run]
#   --dry-run  print the JS payload and where the backup
#              goes without touching your live session.
# =======================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

require_not_root

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

ACTIVE_USER_HOME="$(getent passwd "$ACTUAL_USER" | cut -d: -f6)"
APPSLETSRC="$ACTIVE_USER_HOME/.config/plasma-org.kde.plasma.desktop-appletsrc"
BACKUP_PATH="$APPSLETSRC.pre-plasmaPanel"

PLASMA_VERSION="$(run_as_user plasmashell --version 2>/dev/null | awk '{print $2}')"
if [ -z "$PLASMA_VERSION" ]; then
    log_warn "plasmashell not reachable (off-session?) — Dry-run only."
    DRY_RUN=1
fi
log_info "Detected: Plasma $PLASMA_VERSION"

# --- 1. Pinned apps ----------------------------------------------------------
# Each candidate is added only when its .desktop file is present on the
# system, so a machine without (say) VSCodium simply omits it.
PIN_IDS=(org.kde.konsole org.kde.dolphin firefox-esr vlc org.kde.okular)
PIN_URLS=()
for PID in "${PIN_IDS[@]}"; do
    if [ -f "/usr/share/applications/$PID.desktop" ] || [ -f "$ACTIVE_USER_HOME/.local/share/applications/$PID.desktop" ]; then
        PIN_URLS+=("applications:$PID.desktop")
    else
        log_warn "Skipping pin \"$PID\" — its .desktop file isn't installed."
    fi
done
if [ "${#PIN_URLS[@]}" -eq 0 ]; then
    log_warn "No pinned apps resolved — the panel will be Kickoff + tasks + tray + clock only."
fi

# --- 3. Build the JS payload -------------------------------------------------
# Mirrors the stock defaultPanel layout template's use of the scripting
# API. Old panels are emptied (widget.remove()) then removed; a fresh
# panel is created floating at the bottom. All config writes use the
# documented writeConfig()/readConfig() interface.
build_js() {
    local urls="$1"
    cat << JS
// ---- generated by plasmaPanel.sh ----
var old = panels();
old.forEach(function (p) {
    // empty first; widget.remove() is the shipped/verified operation
    p.widgets().forEach(function (w) { w.remove(); });
    try { p.remove(); } catch (e) {}
});

var panel = new Panel();
panel.height = 40;
// floating is persisted as a [General] config entry (verified on 6.3)
panel.currentConfigGroup = ["General"];
panel.writeConfig("floating", true);

// breathing room on the left
var gap = panel.addWidget("org.kde.plasma.spacer");
gap.currentConfigGroup = ["General"];
try {
    gap.writeConfig("filling", false);
    gap.writeConfig("thickness", 6);
} catch (e) {}

panel.addWidget("org.kde.plasma.kickoff");

// pinned launchers (resolved to installed apps only)
URLS="$urls"
function mkUrlList(u) { return u.split("||"); }
var urls = mkUrlList(URLS);
for (var i = 0; i < urls.length; i++) {
    if (urls[i] === "") continue;
    var icon = panel.addWidget("org.kde.plasma.icon");
    icon.writeConfig("launcherUrl", urls[i]);
    icon.writeConfig("launcherUrlOnlyWhenInstalled", true);
}

// icon-only task manager for running apps (grouped popups)
panel.addWidget("org.kde.plasma.icontasks");

// expanding spacer pushes everything right-of-center apart gracefully
panel.addWidget("org.kde.plasma.spacer");

panel.addWidget("org.kde.plasma.systemtray");

// compact clock (short date + time), then show-desktop
var clock = panel.addWidget("org.kde.plasma.digitalclock");
clock.currentConfigGroup = ["Appearance"];
try {
    clock.writeConfig("dateFormat", "shortDate");
} catch (e) {}

panel.addWidget("org.kde.plasma.showdesktop");
JS
}

PIN_JOINED=""
first_pin=1
for u in "${PIN_URLS[@]}"; do
    if [ "$first_pin" = 1 ]; then
        PIN_JOINED="$u"
        first_pin=0
    else
        PIN_JOINED="$PIN_JOINED||$u"
    fi
done

if [ "$DRY_RUN" = 1 ]; then
    echo -e "${CYAN}--- DRY RUN: payload that WOULD be sent to plasmashell ---${NC}"
    build_js "$PIN_JOINED"
    echo -e "${CYAN}--- backup would go to: ${NC}$BACKUP_PATH"
    echo -e "${YELLOW}Nothing was changed.${NC}"
    exit 0
fi

# --- 2. Backup before touching anything --------------------------------------
if [ ! -f "$APPSLETSRC" ]; then
    log_warn "No existing panel config at $APPSLETSRC — treating as a clean slate."
else
    if [ -e "$BACKUP_PATH" ]; then
        log_info "Existing backup at $BACKUP_PATH — rotating it in place (one backup kept)."
        rm -f "$BACKUP_PATH.bak"
        mv "$BACKUP_PATH" "$BACKUP_PATH.bak"
    fi
    if cp -a "$APPSLETSRC" "$BACKUP_PATH"; then
        log_ok "Panel config backed up to $BACKUP_PATH"
    else
        log_err "Could not back up $APPSLETSRC — aborting."
        exit 1
    fi
fi

DBUS=$(command -v qdbus6 || command -v qdbus)
if [ -z "$DBUS" ]; then
    log_err "Neither qdbus6 nor qdbus found — can't reach plasmashell."
    exit 1
fi

APPLY_OUT="$ACTIVE_USER_HOME/.config/plasmaPanel-apply.log"
if ! run_as_user "$DBUS" org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript \
    >/dev/null 2>"$APPLY_OUT" "$(build_js "$PIN_JOINED")"; then
    log_err "evaluateScript failed ($APPLY_OUT):"
    [ -s "$APPLY_OUT" ] && log_err "  $(tail -1 "$APPLY_OUT")"
    log_err "To restore:  cp '$BACKUP_PATH' '$APPSLETSRC'  then restart plasmashell."
    exit 1
fi

log_ok "Panel rebuilt: single floating bar$( [ -n "$PIN_JOINED" ] && echo " with ${#PIN_URLS[@]} pinned apps," ) icon-tasks, tray, compact clock."
log_warn "A plasmashell restart makes everything fully settle (skip if it already looks right):"
log_warn "  kquitapp6 plasmashell && sleep 2 && kstart6 plasmashell &"